### ISSUE TITLE
Including an image in README

### ISSUE THREAD

**Issue by aecoen** [gge-ucd/Discussion#3]
I am trying to include an image in my README. When previewing in markdown, the image appears just fine, but the README just contains a link that directs to a "404 File not found" page.

Originally I tried using the complete path for the image on my computer. I uploaded the image to my repository and copied the url path which is included below. This still results in the same issue.

![Coyote on Road - Trish Carney.](github.com/amanda_coen/Trish_Carney-Coyote_on_Road.png)

@ryanpeek @Myfanwy

**Comment by ryanpeek** [comment]
I think it might be due to your link...I looked at your README in your repo, and you are using path link (github.com/amanda_coen/LINK_TO_PHOTO), but you actually only need to include the photo name itself, because it's in the same directory:  `![Coyote on Road - Trish Carney.](Trish_Carney-Coyote_on_Road.png)`. I went ahead and fixed it, so next time you work on your repository, make sure to PULL first, then do stuff, so that it incorporates that change.

We'll talk more about relative links and directory linking next week. It's easier when we have some folders to play around with. For now, just recognize that if a file is in the same directory or folder as another file (say your README and .png), you don't have to do anything other than include that filename. If it is in a folder called "images", you would then just use `images/photoname.png`. You only would need to use a full webpage link if it was a photo that didn't live in your folder or repository...(i.e., you don't have a copy, your just linking to it) this is an example of that:

![Relative Links Cartoon](https://imgs.xkcd.com/comics/workaround.png).

Hope this helps @aecoen!
