### ISSUE TITLE
cd issues

### ISSUE THREAD

**Issue by geckyle** [gge-ucd/Discussion#34]
Seems silly, but for the life of me I can't get the cd function to work:

Present working directory:
pwd
/c/Users/kapph/Documents

Attempted change:
cd ~ /c/Users/kapph/Documents/GITHUB\R-DAVIS/w01-fix-readme-geckyle
(There's normally a space where the forward slash is)

error message: No such file or directory

But I go down that file directory path to get to the readme over and over again and it all seems to match up... what am I not seeing?

Also noticed the GIT tab in R studio disappeared? Not sure how to get that tab back... Though shell and my terminal still work... could that be the issue?

**Comment by ryanpeek** [comment]
Hi @geckyle ...are you using a windows computer? And are you in the Terminal in RStudio, or in a script when you are trying to do this? 
One thing to consider is the `~` may not work as you have it printed. (*PS, if you wrap your code chunks with backticks (on my computer its the same key as the ~), they'll highlight/format nicely...so it will be easier to see exactly whats going on...a little Markdown trick)*. The `~` is essentially a shortcut for `/c/Users/kapph/`. Some computers may not recognize it, but in your case, it looks like its actually doubling the path, giving `/c/Users/kapph/c/Users/kapph/` at the start. 

- so if `pwd` == `/c/Users/kapph/Documents`, and you want to go to a folder called "GITHUB R-DAVIS" (*note why putting spaces in filenames can be an issue...try to avoid it, you can use - or _ as spaces*)
- try autocomplete with the TAB key. It's your friend, and can be really helpful because if the path is correct, it will autocomplete, but if not, nothing will show up. You only need a few letters and you can hit TAB. You can also hit TAB TAB in quick succession to see what matches exist (it won't enter them, the computer will simply display a list of options for you and keep your existing path at the prompt). See my attached screen shot of how I might navigate to my project in the Terminal. Note the spot where I type a path and a single "`w`", and then I hit `TAB + TAB` to see what options might match.
 
<img width="848" alt="terminal_cd" src="https://user-images.githubusercontent.com/5864880/35468897-84246500-02dd-11e8-87ff-69dd9581d294.png">

Hopefully that gets you where you need to be. However, if you are using RStudio RProjects, you shouldn't need to be setting a path at all...that's what's so lovely. Simply open the .RProj file by double clicking directly on it, or open project via RStudio, and it should set your directory to where-ever your repository lives on your computer. 

There may be some other underlying git issues we need to address, but let's start with this and see what happens! Good luck! :octocat:

**Comment by geckyle** [comment]
Got it to work! TAB is a huge help! I was missing the space after the \ 

THANKS!!!

_RIP all those hours wasted searching for an empty space_
