### ISSUE TITLE
error with package I don't see in the code 

### ISSUE THREAD

**Issue by mollycle** [gge-ucd/Discussion#41]
I am trying to do last week's assignment, but I keep getting this error:
> #1b
> ggplot(gapminder, aes(x = gdpPercap, y = lifeExp)) +
+   geom_point(aes(color = continent), size = .25) + 
+   scale_x_log10() +
+   geom_smooth(method = 'lm', color = 'black', linetype = 'dashed') +
+   theme_bw()
Error in loadNamespace(name) : there is no package called ‘digest’

I tried exiting and restarting R so that I could run the code again fresh, but I don't know why it is having this package issue when "digest" isn't in the code I am trying to run, any thoughts?

**Comment by MCMaurer** [comment]
This error tells you that one of the functions you're using in your code actually needs to use some other functions, from other packages, in order to work. It looks like something in your code needs to use a function from `digest`.  We call this a *dependency*, because the function you use *depends* on a function from a different package. However, it looks like you don't have `digest` installed.

Did you have issues when you installed `tidyverse` the first time around? I know some folks in the class had issues with this step.

You can try running `install.packages("digest")` to see if you can get `digest` installed.

**Comment by mollycle** [comment]
Thank you! installing "digest" worked, thanks again!
