### ISSUE TITLE
download a package through git

### ISSUE THREAD

**Issue by caparisek** [gge-ucd/Discussion#49]
How can I download a package that seems to be offered through git, and is not searchable through the within R package installation feature?

Do I need to make a pull request? When I followed the git package's instructions to download I get an error message.

For example... 
https://twitter.com/mathematicalm3l/status/1090720774464421889/video/1 
https://github.com/melissanjohnson/pupR 

My steps: 
1) downloaded the package "devtools" 
2) tried running "devtools::install_github("melissanjohnson/pupR")" 
3) I get "invalid input, please try again"
4) "PupR" doesn't work :(

We could all use more pup pics in R, right? 

Thanks @MarthaWohlfeil @MCMaurer @ryanpeek!

**Comment by JepsonNomad** [comment]
The code works on my machine. Is your R up-to-date? Check using `sessionInfo()`.

**Comment by caparisek** [comment]
Thanks. I think so, I downloaded it in January ( v1.1.463 ). 
sessionInfo() gives me the same error message...

**Comment by JepsonNomad** [comment]
Is that your RStudio version? R version should be 3.x.x (mine is 3.4.3). Let's look at your code in class.

**Comment by ryanpeek** [comment]
@caparisek, I think we got this sorted using the following code:

Make sure devtools is installed, and load:
`library(devtools)`

Install the package from github:
`devtools::install_github("melissanjohnson/pupR")`

- A message then gave a list of packages or dependencies that the *pupR* package requires...listed in numbered order, with one of the options being "All".  This can be a bit confusing the first time you see it, because your R console is waiting for you to enter a number that corresponds to one of those options, and then hit **Enter**.

Hopefully it successfully installs everything. Go ahead and load the package:

`library(pupR)`

And run the function:
`pupR()`

And get a picture of a 🐶 🐕 🐩 !  

If this works, please go ahead and close this issue! Thanks.

**Comment by caparisek** [comment]
It works! Thanks
